const COUNTRY_ENUM_MAP = {
  _afghanistan: "Afghanistan",
  _alandIslands: "Åland Islands",
  _albania: "Albania",
  _algeria: "Algeria",
  _americanSamoa: "American Samoa",
  _andorra: "Andorra",
  _angola: "Angola",
  _anguilla: "Anguilla",
  _antarctica: "Antarctica",
  _antiguaAndBarbuda: "Antigua and Barbuda",
  _argentina: "Argentina",
  _armenia: "Armenia",
  _aruba: "Aruba",
  _australia: "Australia",
  _austria: "Austria",
  _azerbaijan: "Azerbaijan",
  _bahamas: "Bahamas",
  _bahrain: "Bahrain",
  _bangladesh: "Bangladesh",
  _barbados: "Barbados",
  _belarus: "Belarus",
  _belgium: "Belgium",
  _belize: "Belize",
  _benin: "Benin",
  _bermuda: "Bermuda",
  _bhutan: "Bhutan",
  _boliviaPlurinationalStateOf: "Bolivia",
  _bonaireSintEustatiusAndSaba: "Bonaire, Sint Eustatius and Saba",
  _bosniaAndHerzegovina: "Bosnia and Herzegovina",
  _botswana: "Botswana",
  _bouvetIsland: "Bouvet Island",
  _brazil: "Brazil",
  _britishIndianOceanTerritory: "British Indian Ocean Territory",
  _bruneiDarussalam: "Brunei Darussalam",
  _bulgaria: "Bulgaria",
  _burkinaFaso: "Burkina Faso",
  _burundi: "Burundi",
  _caboVerde: "Cabo Verde",
  _cambodia: "Cambodia",
  _cameroon: "Cameroon",
  _canada: "Canada",
  _canaryIslands: "Canary Islands",
  _caymanIslands: "Cayman Islands",
  _centralAfricanRepublic: "Central African Republic",
  _ceutaAndMelilla: "Ceuta and Melilla",
  _chad: "Chad",
  _chile: "Chile",
  _china: "China",
  _christmasIsland: "Christmas Island",
  _cocosKeelingIslands: "Cocos (Keeling) Islands",
  _colombia: "Colombia",
  _comoros: "Comoros",
  _congo: "Congo",
  _congoTheDemocraticRepublicOfThe: "Congo, Democratic Republic of the",
  _cookIslands: "Cook Islands",
  _costaRica: "Costa Rica",
  _coteDIvoire: "Côte d'Ivoire",
  _croatia: "Croatia",
  _cuba: "Cuba",
  _curacao: "Curaçao",
  _cyprus: "Cyprus",
  _czechia: "Czechia",
  _denmark: "Denmark",
  _djibouti: "Djibouti",
  _dominica: "Dominica",
  _dominicanRepublic: "Dominican Republic",
  _ecuador: "Ecuador",
  _egypt: "Egypt",
  _elSalvador: "El Salvador",
  _equatorialGuinea: "Equatorial Guinea",
  _eritrea: "Eritrea",
  _estonia: "Estonia",
  _eswatini: "Eswatini",
  _ethiopia: "Ethiopia",
  _falklandIslandsMalvinas: "Falkland Islands (Malvinas)",
  _faroeIslands: "Faroe Islands",
  _fiji: "Fiji",
  _finland: "Finland",
  _france: "France",
  _frenchGuiana: "French Guiana",
  _frenchPolynesia: "French Polynesia",
  _frenchSouthernTerritories: "French Southern Territories",
  _gabon: "Gabon",
  _gambia: "Gambia",
  _georgia: "Georgia",
  _germany: "Germany",
  _ghana: "Ghana",
  _gibraltar: "Gibraltar",
  _greece: "Greece",
  _greenland: "Greenland",
  _grenada: "Grenada",
  _guadeloupe: "Guadeloupe",
  _guam: "Guam",
  _guatemala: "Guatemala",
  _guernsey: "Guernsey",
  _guinea: "Guinea",
  _guineaBissau: "Guinea-Bissau",
  _guyana: "Guyana",
  _haiti: "Haiti",
  _heardIslandAndMcdonaldIslands: "Heard Island and McDonald Islands",
  _holySee: "Holy See",
  _honduras: "Honduras",
  _hongKong: "Hong Kong",
  _hungary: "Hungary",
  _iceland: "Iceland",
  _india: "India",
  _indonesia: "Indonesia",
  _iranIslamicRepublicOf: "Iran",
  _iraq: "Iraq",
  _ireland: "Ireland",
  _isleOfMan: "Isle of Man",
  _israel: "Israel",
  _italy: "Italy",
  _jamaica: "Jamaica",
  _japan: "Japan",
  _jersey: "Jersey",
  _jordan: "Jordan",
  _kazakhstan: "Kazakhstan",
  _kenya: "Kenya",
  _kiribati: "Kiribati",
  _koreaTheDemocraticPeoplesRepublicOf: "North Korea",
  _koreaTheRepublicOf: "South Korea",
  _kosovo: "Kosovo",
  _kuwait: "Kuwait",
  _kyrgyzstan: "Kyrgyzstan",
  _laoPeoplesDemocraticRepublic: "Laos",
  _latvia: "Latvia",
  _lebanon: "Lebanon",
  _lesotho: "Lesotho",
  _liberia: "Liberia",
  _libya: "Libya",
  _liechtenstein: "Liechtenstein",
  _lithuania: "Lithuania",
  _luxembourg: "Luxembourg",
  _macao: "Macao",
  _madagascar: "Madagascar",
  _malawi: "Malawi",
  _malaysia: "Malaysia",
  _maldives: "Maldives",
  _mali: "Mali",
  _malta: "Malta",
  _marshallIslands: "Marshall Islands",
  _martinique: "Martinique",
  _mauritania: "Mauritania",
  _mauritius: "Mauritius",
  _mayotte: "Mayotte",
  _mexico: "Mexico",
  _micronesiaFederatedStatesOf: "Micronesia",
  _moldovaTheRepublicOf: "Moldova",
  _monaco: "Monaco",
  _mongolia: "Mongolia",
  _montenegro: "Montenegro",
  _montserrat: "Montserrat",
  _morocco: "Morocco",
  _mozambique: "Mozambique",
  _myanmar: "Myanmar",
  _namibia: "Namibia",
  _nauru: "Nauru",
  _nepal: "Nepal",
  _netherlands: "Netherlands",
  _newCaledonia: "New Caledonia",
  _newZealand: "New Zealand",
  _nicaragua: "Nicaragua",
  _niger: "Niger",
  _nigeria: "Nigeria",
  _niue: "Niue",
  _norfolkIsland: "Norfolk Island",
  _northernMarianaIslands: "Northern Mariana Islands",
  _northMacedonia: "North Macedonia",
  _norway: "Norway",
  _oman: "Oman",
  _pakistan: "Pakistan",
  _palau: "Palau",
  _palestineStateOf: "Palestine",
  _panama: "Panama",
  _papuaNewGuinea: "Papua New Guinea",
  _paraguay: "Paraguay",
  _peru: "Peru",
  _philippines: "Philippines",
  _pitcairn: "Pitcairn",
  _poland: "Poland",
  _portugal: "Portugal",
  _puertoRico: "Puerto Rico",
  _qatar: "Qatar",
  _reunion: "Réunion",
  _romania: "Romania",
  _russianFederation: "Russia",
  _rwanda: "Rwanda",
  _saintBarthelemy: "Saint Barthélemy",
  _saintHelenaAscensionAndTristanDaCunha: "Saint Helena",
  _saintKittsAndNevis: "Saint Kitts and Nevis",
  _saintLucia: "Saint Lucia",
  _saintMartinFrenchPart: "Saint Martin",
  _saintPierreAndMiquelon: "Saint Pierre and Miquelon",
  _saintVincentAndTheGrenadines: "Saint Vincent and the Grenadines",
  _samoa: "Samoa",
  _sanMarino: "San Marino",
  _saoTomeAndPrincipe: "São Tomé and Príncipe",
  _saudiArabia: "Saudi Arabia",
  _senegal: "Senegal",
  _serbia: "Serbia",
  _seychelles: "Seychelles",
  _sierraLeone: "Sierra Leone",
  _singapore: "Singapore",
  _sintMaartenDutchPart: "Sint Maarten",
  _slovakia: "Slovakia",
  _slovenia: "Slovenia",
  _solomonIslands: "Solomon Islands",
  _somalia: "Somalia",
  _southAfrica: "South Africa",
  _southGeorgiaAndTheSouthSandwichIslands: "South Georgia and the South Sandwich Islands",
  _southSudan: "South Sudan",
  _spain: "Spain",
  _sriLanka: "Sri Lanka",
  _sudan: "Sudan",
  _suriname: "Suriname",
  _svalbardAndJanMayen: "Svalbard and Jan Mayen",
  _sweden: "Sweden",
  _switzerland: "Switzerland",
  _syrianArabRepublic: "Syria",
  _taiwan: "Taiwan",
  _tajikistan: "Tajikistan",
  _tanzaniaTheUnitedRepublicOf: "Tanzania",
  _thailand: "Thailand",
  _timorLeste: "Timor-Leste",
  _togo: "Togo",
  _tokelau: "Tokelau",
  _tonga: "Tonga",
  _trinidadAndTobago: "Trinidad and Tobago",
  _tunisia: "Tunisia",
  _turkiye: "Türkiye",
  _turkmenistan: "Turkmenistan",
  _turksAndCaicosIslands: "Turks and Caicos Islands",
  _tuvalu: "Tuvalu",
  _uganda: "Uganda",
  _ukraine: "Ukraine",
  _unitedArabEmirates: "United Arab Emirates",
  _unitedKingdom: "United Kingdom",
  _unitedStates: "United States",
  _unitedStatesMinorOutlyingIslands: "United States Minor Outlying Islands",
  _uruguay: "Uruguay",
  _uzbekistan: "Uzbekistan",
  _vanuatu: "Vanuatu",
  _venezuelaBolivarianRepublicOf: "Venezuela",
  _vietNam: "Viet Nam",
  _virginIslandsBritish: "Virgin Islands (British)",
  _virginIslandsUS: "Virgin Islands (U.S.)",
  _wallisAndFutunaIslands: "Wallis and Futuna Islands",
  _westernSahara: "Western Sahara",
  _yemen: "Yemen",
  _zambia: "Zambia",
  _zimbabwe: "Zimbabwe"
};

function formatCountry(countryEnum) {
  return COUNTRY_ENUM_MAP[countryEnum] ?? countryEnum;
}

export function formatAddress({
  contact,
  addr1,
  addr2,
  city,
  state,
  zip,
  country
}) {
  const street = [addr1, addr2].filter(Boolean).join(" ");
  const cityStateZip = [city, state, zip].filter(Boolean).join(", ");
  const countryDisplay = country ? formatCountry(country) : null;

  return [contact, street, cityStateZip, countryDisplay].filter(Boolean).join("\n");
}
