const arr = [
  {
    Status: "Sent",
    CompanyOrAccount: "SFDC Computing",
    LastModifiedDate: "2025-10-21T16:15:30.000Z",
    IsDeleted: false,
    Email: "test2@gmail.com",
    HasResponded: false,
    DoNotCall: false,
    FirstName: "Carol",
    HasOptedOutOfEmail: false,
    HasOptedOutOfFax: false,
    ContactId: "003bm00000S17c1AAB",
    SystemModstamp: "2025-10-21T16:15:30.000Z",
    CreatedById: "005bm00000FwIFFAA3",
    CampaignId: "701bm00001FNGNyAAP",
    Phone: "(415)555-1212",
    CreatedDate: "2025-10-21T16:15:30.000Z",
    Id: "00vbm00000ErJdxAAF",
    LastName: "Ruiz",
    LastModifiedById: "005bm00000FwIFFAA3"
  },
  {
    Status: "Sent",
    CompanyOrAccount: "United Oil & Gas Cor (2 more) ...",
    LastModifiedDate: "2025-10-21T16:15:30.000Z",
    IsDeleted: false,
    Email: "test1@gmail.com",
    HasResponded: false,
    DoNotCall: false,
    HasOptedOutOfEmail: false,
    HasOptedOutOfFax: false,
    ContactId: "003bm00000RyRpKAAV",
    SystemModstamp: "2025-10-21T16:15:30.000Z",
    CreatedById: "005bm00000FwIFFAA3",
    CampaignId: "701bm00001FNGNyAAP",
    CreatedDate: "2025-10-21T16:15:30.000Z",
    Id: "00vbm00000ErJdyAAF",
    LastName: "Chen",
    LastModifiedById: "005bm00000FwIFFAA3"
  }
];

const payload = [
  {
    LastName: "Ruiz",
    FirstName: "Carol",
    Email: "test2@gmail.com",
    CampaignName: "Icontact Campaign"
  },
  {
    LastName: "Chen",
    FirstName: null,
    Email: "test1@gmail.com",
    CampaignName: "Icontact Campaign"
  }
];

const res = {
  contacts: [
    {
      contactId: "114593740",
      prefix: "",
      firstName: "Carol",
      lastName: "Ruiz",
      suffix: "",
      street: "",
      street2: "",
      city: "",
      state: "",
      postalCode: "",
      phone: "",
      fax: "",
      business: "",
      email: "test2@gmail.com",
      createDate: "2025-10-21 14:58:56",
      bounceCount: "",
      status: null,
      annualrevenue: null,
      birthday: null,
      cartieroldproleftover: null,
      clientsource: null,
      custnum: null,
      dateofproposal: null,
      dateofwedding: null,
      department: null,
      designerjewerly: null,
      emailaddress2: null,
      engagement_ring_info_date: null,
      engagementringpurchasedate: null,
      engagementringsandweddingbands: null,
      events: null,
      facebookurl: null,
      fullname: null,
      homephone: null,
      industry: null,
      itemname: null,
      jobtitle: null,
      linkedinurl: null,
      mobilephone: null,
      moreaboutyou: null,
      nonopener: null,
      notes: null,
      numberemployees: null,
      onetimemagazine: null,
      oneyearnonopener: null,
      ongoingmagazine: null,
      rfm: null,
      serviceonly: null,
      source_homepage: null,
      source_signuppage: null,
      storenumber: null,
      twitterhandle: null,
      url: null,
      watches: null,
      websiteurl: null,
      winningbid: null
    },
    {
      contactId: "114593741",
      prefix: "",
      firstName: "",
      lastName: "Chen",
      suffix: "",
      street: "",
      street2: "",
      city: "",
      state: "",
      postalCode: "",
      phone: "",
      fax: "",
      business: "",
      email: "test1@gmail.com",
      createDate: "2025-10-21 14:58:57",
      bounceCount: "",
      status: null,
      annualrevenue: null,
      birthday: null,
      cartieroldproleftover: null,
      clientsource: null,
      custnum: null,
      dateofproposal: null,
      dateofwedding: null,
      department: null,
      designerjewerly: null,
      emailaddress2: null,
      engagement_ring_info_date: null,
      engagementringpurchasedate: null,
      engagementringsandweddingbands: null,
      events: null,
      facebookurl: null,
      fullname: null,
      homephone: null,
      industry: null,
      itemname: null,
      jobtitle: null,
      linkedinurl: null,
      mobilephone: null,
      moreaboutyou: null,
      nonopener: null,
      notes: null,
      numberemployees: null,
      onetimemagazine: null,
      oneyearnonopener: null,
      ongoingmagazine: null,
      rfm: null,
      serviceonly: null,
      source_homepage: null,
      source_signuppage: null,
      storenumber: null,
      twitterhandle: null,
      url: null,
      watches: null,
      websiteurl: null,
      winningbid: null
    }
  ]
};

const listRes = {
  lists: [
    {
      listId: "193089",
      name: "Icontact Campaign",
      publicname: "",
      description: "example description",
      emailOwnerOnChange: 0,
      welcomeOnManualAdd: 0,
      welcomeOnSignupAdd: 0,
      welcomeMessageId: ""
    }
  ]
};
